/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lastprofstanding

class App {
    companion object {
        fun main() {
            println("Main entrypoint.")
        }
    }
}

fun main() {
    App.main()
}
