/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package lastprofstanding

import lastprofstanding.engine.Engine
import lastprofstanding.engine.Level
import lastprofstanding.engine.SimulationSpeed
import lastprofstanding.engine.grid.*

class MyCell : Cell(true), InteractiveCell<MyCell> {
    override fun testForSpawningNewCell(grid: Grid, position: GridPosition): Pair<MyCell, GridPosition> {
        return Pair(MyCell(), position + GridPosition(0, 1))
    }

    override fun clone(): Cell {
        return MyCell()
    }

    override val icon: Int = 5
    override val textRepresentation = "M"
}
class App {
    companion object {
        fun main() {
           val engine = Engine.getInstance()
            engine.load(Level.BASIC)
            engine.startSimulation({ grid, stats ->
                println(grid.getTextRepresentation())
                println(stats)
                if (stats.timeSpentPlaying >= 30) {
                    engine.stopSimulation()
                }
            }, SimulationSpeed.X1)
        }
    }
}

fun main() {
    App.main()
}
