package lastprofstanding.engine.grid

enum class TileType {
    FLOOR,
    WALL_BOTTOM, WALL_BOTTOM_LEFT, WALL_BOTTOM_RIGHT, WALL_TOP, WALL_TOP_LEFT, WALL_TOP_RIGHT, WALL_VERTICAL,
    BOARD_BOTTOM_LEFT, BOARD_BOTTOM_MIDDLE, BOARD_BOTTOM_RIGHT, BOARD_TOP_LEFT, BOARD_TOP_MIDDLE, BOARD_TOP_RIGHT,
    CANVAS_BOTTOM_LEFT, CANVAS_BOTTOM_RIGHT, CANVAS_TOP_LEFT, CANVAS_TOP_RIGHT,
    TABLE_LEFT, TABLE_LEFT_DECO, TABLE_RIGHT;

}